- name: provisioning the cart service
  hosts: cart
  become: yes
  tasks: 

  - name: Disable the default node js
    ansible.builtin.command: dnf module disable nodejs -y

  - name: Enable the nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Installing nodejs
    ansible.builtin.dnf:
     name: nodejs
     state: present

  - name: adding application user
    ansible.builtin.user:
     name: roboshop
     shell: /sbin/nologin
     comment: "roboshop system user"
     state: present
     system: true
     home: /app

  - name: setting up a directory
    ansible.builtin.file:
     path: /app
     state: directory

  - name: Downloading the application code
    ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
     dest: /tmp/cart.zip

  - name: unzipping application code to app directory
    ansible.builtin.unarchive:
     src: /tmp/cart.zip
     dest: /app
     remote_src: true

  - name: Downloading the dependencies using build tool npm
    community.general.npm:
     path: /app

  - name: copying cart service configuration
    ansible.builtin.copy:
     src: cart.service
     dest: /etc/systemd/system/cart.service

  - name: reloading system daemon
    ansible.builtin.systemd_service:
     daemon_reload: true

  - name: enable and start the system services
    ansible.builtin.service:
     name: cart
     enabled: yes
     state: started            


