- name: provisioning the user application
  hosts: user
  become: yes
  tasks:

  - name: Disable the default nodejs module
    ansible.builtin.command: "dnf module disable nodejs -y"

  - name: Enable the nodejs 20
    ansible.builtin.command: "dnf module enable nodejs:20 -y"

  - name: Installing node js
    ansible.builtin.dnf:
     name: nodejs  
     state: present  

  - name: adding system-user
    ansible.builtin.user:
     name: roboshop
     shell: /sbin/nologin
     home: /app
     comment: "roboshop system user"
     system: true   

  - name: creating the app directory
    ansible.builtin.file:
     path: /app
     state: directory

  - name: Download application code from directory
    ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
     dest: /tmp/user.zip

  - name: unzip application code in /app folder
    ansible.builtin.unarchive:    
     src: /tmp/user.zip
     dest: /app
     remote_src: true

  - name: installing dependencies of package.json using npm
    community.general.npm:
     path: /app

  - name: reload daemon service
    ansible.builtin.systemd_service:
     daemon_reload: true

  - name: start and enable system services
    ansible.builtin.service:
     name: user
     state: started
     enabled: yes        



    
  